name: mason_bricks
description: Collection of bricks for scaffolding
version: 0.1.0
environment: 
  sdk: '>=2.18.7 <3.0.0'
dependencies: 
  path: ^1.8.3
  yaml: ^3.1.1
  yaml_extension: ^1.0.2
dev_dependencies: 
  lints: ^2.0.0
  test: ^1.16.0
