export 'data/{{feature}}_model.dart';
export 'data/{{feature}}_repository_impl.dart';
export 'domain/{{feature}}_repository.dart';
export 'domain/{{feature}}.dart';
export 'presentation/bloc/{{feature}}_edit_bloc.dart';
export 'presentation/bloc/{{feature}}_read_bloc.dart';
export 'presentation/views/{{feature}}_edit_view.dart';
export 'presentation/views/{{feature}}_read_view.dart';
export 'presentation/widgets/{{feature}}_widget.dart';
