name: scaffolding_test
on: 
  push:
    branches:
      - main
  
  pull_request:

jobs:
  setup:
    defaults:
      run:
        working-directory: tests/scaffolding
    
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3.3.0
    - uses: subosito/flutter-action@v2
      with:
        channel: 'stable'

    - run: flutter --version
      shell: bash
    - run: dart --version
      shell: bash
    - run: dart test
      shell: bash
    
